version: "3.8"

services:
  db:
    container_name: "wetbat-db"
    image: postgres:alpine
    restart: always
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wetbat
    volumes:
      - ./data:/data/postgres
